# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import cloud_pb2 as cloud__pb2


class ComputeServiceStub(object):
    """Сервис, который будет запущен на Go (Compute Node)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateInstance = channel.unary_unary(
                '/cloud.ComputeService/CreateInstance',
                request_serializer=cloud__pb2.CreateInstanceRequest.SerializeToString,
                response_deserializer=cloud__pb2.InstanceResponse.FromString,
                )
        self.DeleteInstance = channel.unary_unary(
                '/cloud.ComputeService/DeleteInstance',
                request_serializer=cloud__pb2.DeleteInstanceRequest.SerializeToString,
                response_deserializer=cloud__pb2.InstanceResponse.FromString,
                )
        self.GetContainerStats = channel.unary_unary(
                '/cloud.ComputeService/GetContainerStats',
                request_serializer=cloud__pb2.ContainerStatsRequest.SerializeToString,
                response_deserializer=cloud__pb2.ContainerStatsResponse.FromString,
                )
        self.GetNodeStats = channel.unary_unary(
                '/cloud.ComputeService/GetNodeStats',
                request_serializer=cloud__pb2.NodeStatsRequest.SerializeToString,
                response_deserializer=cloud__pb2.NodeStatsResponse.FromString,
                )


class ComputeServiceServicer(object):
    """Сервис, который будет запущен на Go (Compute Node)
    """

    def CreateInstance(self, request, context):
        """Запрос на создание ВМ (Docker контейнера)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteInstance(self, request, context):
        """Запрос на удаление ВМ
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetContainerStats(self, request, context):
        """Запрос статистики конкретного контейнера (Continuous monitoring)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNodeStats(self, request, context):
        """Запрос статистики всей ноды (Cluster metrics)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ComputeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateInstance': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateInstance,
                    request_deserializer=cloud__pb2.CreateInstanceRequest.FromString,
                    response_serializer=cloud__pb2.InstanceResponse.SerializeToString,
            ),
            'DeleteInstance': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteInstance,
                    request_deserializer=cloud__pb2.DeleteInstanceRequest.FromString,
                    response_serializer=cloud__pb2.InstanceResponse.SerializeToString,
            ),
            'GetContainerStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetContainerStats,
                    request_deserializer=cloud__pb2.ContainerStatsRequest.FromString,
                    response_serializer=cloud__pb2.ContainerStatsResponse.SerializeToString,
            ),
            'GetNodeStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNodeStats,
                    request_deserializer=cloud__pb2.NodeStatsRequest.FromString,
                    response_serializer=cloud__pb2.NodeStatsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cloud.ComputeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ComputeService(object):
    """Сервис, который будет запущен на Go (Compute Node)
    """

    @staticmethod
    def CreateInstance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cloud.ComputeService/CreateInstance',
            cloud__pb2.CreateInstanceRequest.SerializeToString,
            cloud__pb2.InstanceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteInstance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cloud.ComputeService/DeleteInstance',
            cloud__pb2.DeleteInstanceRequest.SerializeToString,
            cloud__pb2.InstanceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetContainerStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cloud.ComputeService/GetContainerStats',
            cloud__pb2.ContainerStatsRequest.SerializeToString,
            cloud__pb2.ContainerStatsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetNodeStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cloud.ComputeService/GetNodeStats',
            cloud__pb2.NodeStatsRequest.SerializeToString,
            cloud__pb2.NodeStatsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
